*Сингулярное разложение*— декомпозиция вещественной матрицы с целью ее приведения к каноническому виду. Сингулярное разложение является удобным методом при работе с матрицами. Оно показывает геометрическую структуру матрицы и позволяет наглядно представить имеющиеся данные. 

**Постановка задачи**

Популярным применением SVD является уменьшение размерности.

Данные с большим количеством признаков, например больше признаков (столбцов), чем наблюдений (строк), могут быть сведены к меньшему подмножеству признаков, которые наиболее важны для задачи прогнозирования.

В результате, получается матрица с более низким рангом, которая, как говорят, аппроксимирует исходную матрицу.

Найти исходную матрицу для матрицы $A$.

\begin{equation*}
A = \left(
\begin{array}{cccc}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15 & 16 & 17 & 18 & 19 & 20\\
21 & 22 & 23 & 24 & 25 & 26 & 27 & 28 & 29 & 30
\end{array}
\right)
\end{equation*}

**Описание структуры исходных данных**

Сингулярным разложением матрицы $M$ порядка $m\times n$ является разложение следующего вида:

${\displaystyle M=U\Sigma V^{*},}$
где $\Sigma$  — матрица размера $m\times n$ с неотрицательными элементами, у которой элементы, лежащие на главной диагонали — это сингулярные числа (а все элементы, не лежащие на главной диагонали, являются нулевыми), а матрицы $U$ (порядка $m$) и $V$ (порядка $n$) — это две унитарные матрицы, состоящие из левых и правых сингулярных векторов соответственно (а $V^*$ — это сопряжённо-транспонированная матрица к $V$).

**Описание используемых функций и их параметров**

sklearn.decomposition.TruncatedSVD(n_components=2) - функция, которая уменьшает размерность с помощью усеченного SVD (также известного как LSA).
>- n_components=2 - желаемая размерность выходных данных.

svd.fit(A) - Подгонка модели к обучающим данным А.
>- A - набор данных.

svd.transform(A) - Выполняет уменьшение размерности на А.
>- A - набор данных.

**Решение задачи**

Сначала определим матрицу $A$. Рассчитаем SVD, и выбирем только первые два признака. Элементы рекомбинируем, чтобы дать точное воспроизведение исходной матрицы. Наконец, выполняем преобразование.

In [ ]:
from numpy import array
from sklearn.decomposition import TruncatedSVD
# define array
A = array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print("Матрица А:")
print(A)
# svd
svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)

Матрица А:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


**Визуализация результата**

In [ ]:
print("Исходная матрица для А:")
print(result)

Исходная матрица для А:
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


**Интерпретация результата**

В результате удалось получить исходную матрицу для матрицы А. Таким образом количество признаков(10) сократилось к меньшему подмножеству признаков(2), которые наиболее важны.

**Задания для самостоятельной работы**
1. Найдите такой вектор $w$, чтобы отражение относительно плоскости, ортогональной вектору $w$, переводило вектор (4, 2, 4)′ в вектор ($a$, 0, 0), $a$ > 0. Выпишите матрицу соответствующего отражения.

2. Пусть $y$ и $x$ — это два произвольных вектора. Найдите:
> 1. Проекцию вектора y на прямую, порождённую вектором $x$;
> 2. Проекцию вектора y на плоскость, ортогональную вектору $x$;
> 3. Отражение вектора y относительно плоскости, ортогональной вектору $x$;
